### PR TITLE
np.float is deprecated in numpy==1.24.0

### PR DESCRIPTION
**Pull request by adrabent**
The using of `numpy.float` will throw an error in the most recent numpy release and just needs to be replaced.

References:
https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

### CODE REVIEW

**Comment by revoltek** [comment]
This would double the size of the weight tables in h5parms, in practice makes everything 50% larger as every soltab has a weight table associated... is this the best/only way to proceed?

**Comment by adrabent** [comment]
We may need to go through the changes to see what precision is exactly needed. There is also float16 if this would reduce the precision. What is the precision of the old numpy.float() ?

**Comment by mhardcastle** [comment]
Old np.float is the same as Python float, i.e. np.float64, surely?

**Comment by gmloose** [comment]
In other words, @revoltek, this change would not double the size of the weight tables, but half them, since we're changing `np.float64` (the equivalent of the deprecated `np.float`) into `np.float32`. Or am I missing something here?

**Comment by revoltek** [comment]
ok, these are changes just in a few operations, the main lib is indeed using float16 for weights (that currently are just 1 and 0, for good/flagged data)

**Comment by revoltek** [comment]
ok, these are changes just in a few operations, the main lib is indeed using float16 for weights (that currently are just 1 and 0, for good/flagged data)

**Pull request merged**
